# Generated by Django 5.1.7 on 2025-03-08 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('icon', models.CharField(blank=True, help_text='FontAwesome图标类名', max_length=50, verbose_name='图标类名')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('pinyin', models.CharField(blank=True, help_text='自动生成，用于搜索', max_length=200, verbose_name='拼音')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('url', models.URLField(verbose_name='链接地址')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='link_icons/', verbose_name='图标')),
                ('icon_class', models.CharField(blank=True, help_text='FontAwesome图标类名', max_length=50, verbose_name='图标类名')),
                ('visibility', models.CharField(choices=[('public', '所有人可见'), ('authenticated', '仅登录用户可见')], default='public', max_length=20, verbose_name='可见性')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('pinyin', models.CharField(blank=True, help_text='自动生成，用于搜索', max_length=500, verbose_name='拼音')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='navigator.category', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '链接',
                'verbose_name_plural': '链接',
                'ordering': ['category', 'order', 'title'],
            },
        ),
    ]
