# Generated by Django 5.1.7 on 2025-03-09 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0002_link_click_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='icon',
            new_name='icon_class',
        ),
    ]
