# Generated by Django 5.1.7 on 2025-03-09 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0004_alter_link_options_link_is_pinned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='文件夹名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='navigator.folder', verbose_name='父文件夹')),
            ],
            options={
                'verbose_name': '文件夹',
                'verbose_name_plural': '文件夹',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='文件名')),
                ('file', models.FileField(upload_to='downloads/', verbose_name='文件')),
                ('description', models.TextField(blank=True, null=True, verbose_name='文件描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='下载次数')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='navigator.folder', verbose_name='所属文件夹')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
                'ordering': ['name'],
            },
        ),
    ]
