# Generated by Django 5.1.7 on 2025-03-09 07:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0005_folder_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='share_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='file',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='查看次数'),
        ),
    ]
