# Generated by Django 5.1.7 on 2025-03-09 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0006_file_share_code_file_view_count'),
    ]

    operations = [
    ]
